import { User, ChequeRequest } from '../types';
import { UserRole, ChequeStatus } from './constants';

export const mockUsers: User[] = [
    {
        id: 'u1',
        name: 'Admin User',
        email: 'admin@bank.com',
        role: UserRole.ADMIN,
        employeeId: 'ADM001',
    },
    {
        id: 'u2',
        name: 'John Doe',
        email: 'john@gmail.com',
        role: UserRole.USER,
    },
    {
        id: 'u3',
        name: 'Sarah Smith',
        email: 'sarah.cs@bank.com',
        role: UserRole.CUSTOMER_SERVICE,
        office: 'Customer Service',
        employeeId: 'CS001',
    },
    {
        id: 'u4',
        name: 'Mike Johnson',
        email: 'mike.bc@bank.com',
        role: UserRole.BRANCH_CONTROLLER,
        office: 'Branch Controller',
        employeeId: 'BC001',
    },
    {
        id: 'u5',
        name: 'Alice Wong',
        email: 'alice.tl@bank.com',
        role: UserRole.TELLER,
        office: 'Teller',
        employeeId: 'TL001',
    },
    {
        id: 'u6',
        name: 'Robert Brown',
        email: 'robert.tr@bank.com',
        role: UserRole.TREASURY,
        office: 'Treasury',
        employeeId: 'TR001',
    },
];

// use a fixed "now" so that server and client always see the same timestamps
const NOW = new Date('2026-03-06T17:15:00.000Z').getTime();

export const mockCheques: ChequeRequest[] = [
    {
        id: 'chq-101',
        accountName: 'John Doe',
        accountNumber: '1234567890',
        chequeNumber: 'CHQ-000101',
        amount: 50000,
        requestType: 'BOX',
        boxAction: Math.random() > 0.5 ? 'REQUEST' : 'RETURN', numberOfBoxes: Math.floor(Math.random() * 10) + 1,
        phoneNumber: '+2348012345678',
        bankBranch: 'Lagos Main',
        status: ChequeStatus.SUBMITTED,
        // one hour before the fixed timestamp
        submittedAt: new Date(NOW - 3600000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Customer Service',
        logs: [
            {
                id: 'log-1',
                chequeId: 'chq-101',
                action: 'SUBMITTED',
                performedBy: 'John Doe',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 3600000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-102',
        accountName: 'Jane Smith',
        accountNumber: '0987654321',
        chequeNumber: 'CHQ-000102',
        amount: 120000,
        requestType: 'WITHDRAWAL',
        oidMatch: 'OID-'+Math.floor(Math.random()*900000+100000), imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
        phoneNumber: '+2348098765432',
        bankBranch: 'Abuja Central',
        status: ChequeStatus.PAID,
        // one day before the fixed timestamp
        submittedAt: new Date(NOW - 86400000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'DONE',
        logs: [], // Detailed logs can be added as needed
    },
    {
        id: 'chq-103',
        accountName: 'Alice Johnson',
        accountNumber: '1122334455',
        chequeNumber: 'CHQ-000103',
        amount: 85000,
        requestType: 'BOX',
        boxAction: Math.random() > 0.5 ? 'REQUEST' : 'RETURN', numberOfBoxes: Math.floor(Math.random() * 10) + 1,
        phoneNumber: '+2348033334444',
        bankBranch: 'Victoria Island',
        status: ChequeStatus.APPROVED_BY_CUSTOMER_SERVICE,
        submittedAt: new Date(NOW - 7200000).toISOString(), // 2 hours ago
        submittedBy: 'u2',
        currentOffice: 'Branch Controller',
        logs: [
            {
                id: 'log-3',
                chequeId: 'chq-103',
                action: 'SUBMITTED',
                performedBy: 'Alice Johnson',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 7200000).toISOString(),
            },
            {
                id: 'log-4',
                chequeId: 'chq-103',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 3600000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-104',
        accountName: 'Michael Obi',
        accountNumber: '5544332211',
        chequeNumber: 'CHQ-000104',
        amount: 250000,
        requestType: 'WITHDRAWAL',
        oidMatch: 'OID-'+Math.floor(Math.random()*900000+100000), imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
        phoneNumber: '+2348055556666',
        bankBranch: 'Lekki Phase 1',
        status: ChequeStatus.APPROVED_BY_CUSTOMER_SERVICE,
        submittedAt: new Date(NOW - 8000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Branch Controller',
        logs: [
            {
                id: 'log-5',
                chequeId: 'chq-104',
                action: 'SUBMITTED',
                performedBy: 'Michael Obi',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 8000000).toISOString(),
            },
            {
                id: 'log-6',
                chequeId: 'chq-104',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 4000000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-105',
        accountName: 'Oluwaseun Adeyemi',
        accountNumber: '2233445566',
        chequeNumber: 'CHQ-000105',
        amount: 320000,
        requestType: 'WITHDRAWAL',
        oidMatch: 'OID-'+Math.floor(Math.random()*900000+100000), imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
        phoneNumber: '+2348122223333',
        bankBranch: 'Ikeja',
        status: ChequeStatus.SUBMITTED,
        submittedAt: new Date(NOW - 1500000).toISOString(), // ~25 mins ago
        submittedBy: 'u2',
        currentOffice: 'Customer Service',
        logs: [
            {
                id: 'log-7',
                chequeId: 'chq-105',
                action: 'SUBMITTED',
                performedBy: 'Oluwaseun Adeyemi',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 1500000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-106',
        accountName: 'Fatima Bello',
        accountNumber: '8877665544',
        chequeNumber: 'CHQ-000106',
        amount: 850000,
        requestType: 'DEPOSIT',
        numberOfBoxes: Math.floor(Math.random() * 5) + 1, denominations: [{bill: '1000 Naira', count: Math.floor(850000/1000), total: 850000}],
        phoneNumber: '+2348077778888',
        bankBranch: 'Abuja Central',
        status: ChequeStatus.SUBMITTED,
        submittedAt: new Date(NOW - 7500000).toISOString(), // ~2 hours ago
        submittedBy: 'u2',
        currentOffice: 'Customer Service',
        logs: [
            {
                id: 'log-8',
                chequeId: 'chq-106',
                action: 'SUBMITTED',
                performedBy: 'Fatima Bello',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 7500000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-107',
        accountName: 'Chinedu Eze',
        accountNumber: '9988776655',
        chequeNumber: 'CHQ-000107',
        amount: 45000,
        requestType: 'BOX',
        boxAction: Math.random() > 0.5 ? 'REQUEST' : 'RETURN', numberOfBoxes: Math.floor(Math.random() * 10) + 1,
        phoneNumber: '+2348099990000',
        bankBranch: 'Port Harcourt',
        status: ChequeStatus.RETURNED_FOR_ADJUSTMENT,
        submittedAt: new Date(NOW - 18000000).toISOString(), // ~5 hours ago
        submittedBy: 'u2',
        currentOffice: 'Customer Service',
        logs: [
            {
                id: 'log-9',
                chequeId: 'chq-107',
                action: 'SUBMITTED',
                performedBy: 'Chinedu Eze',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 18000000).toISOString(),
            },
            {
                id: 'log-10',
                chequeId: 'chq-107',
                action: 'RETURNED_FOR_ADJUSTMENT',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 10000000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-108',
        accountName: 'Grace Okafor',
        accountNumber: '4455667788',
        chequeNumber: 'CHQ-000108',
        amount: 1500000,
        requestType: 'DEPOSIT',
        numberOfBoxes: Math.floor(Math.random() * 5) + 1, denominations: [{bill: '1000 Naira', count: Math.floor(1500000/1000), total: 1500000}],
        phoneNumber: '+2348144445555',
        bankBranch: 'Victoria Island',
        status: ChequeStatus.VERIFIED_BY_BRANCH_CONTROLLER,
        submittedAt: new Date(NOW - 20000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Treasury',
        logs: [
            {
                id: 'log-11',
                chequeId: 'chq-108',
                action: 'SUBMITTED',
                performedBy: 'Grace Okafor',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 20000000).toISOString(),
            },
            {
                id: 'log-12',
                chequeId: 'chq-108',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 18000000).toISOString(),
            },
            {
                id: 'log-13',
                chequeId: 'chq-108',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 15000000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-109',
        accountName: 'David Nwachukwu',
        accountNumber: '3322110099',
        chequeNumber: 'CHQ-000109',
        amount: 25000,
        requestType: 'BOX',
        boxAction: Math.random() > 0.5 ? 'REQUEST' : 'RETURN', numberOfBoxes: Math.floor(Math.random() * 10) + 1,
        phoneNumber: '+2348033332222',
        bankBranch: 'Surulere',
        status: ChequeStatus.SUBMITTED,
        submittedAt: new Date(NOW - 500000).toISOString(), // ~8 mins ago
        submittedBy: 'u2',
        currentOffice: 'Customer Service',
        logs: [
            {
                id: 'log-14',
                chequeId: 'chq-109',
                action: 'SUBMITTED',
                performedBy: 'David Nwachukwu',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 500000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-110',
        accountName: 'Zainab Aliyu',
        accountNumber: '7778889990',
        chequeNumber: 'CHQ-000110',
        amount: 550000,
        requestType: 'DEPOSIT',
        numberOfBoxes: Math.floor(Math.random() * 5) + 1, denominations: [{bill: '1000 Naira', count: Math.floor(550000/1000), total: 550000}],
        phoneNumber: '+2348066667777',
        bankBranch: 'Kano Main',
        status: ChequeStatus.VERIFIED_BY_BRANCH_CONTROLLER,
        submittedAt: new Date(NOW - 25000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Teller',
        logs: [
            {
                id: 'log-15',
                chequeId: 'chq-110',
                action: 'SUBMITTED',
                performedBy: 'Zainab Aliyu',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 25000000).toISOString(),
            },
            {
                id: 'log-16',
                chequeId: 'chq-110',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 22000000).toISOString(),
            },
            {
                id: 'log-17',
                chequeId: 'chq-110',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 19000000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-111',
        accountName: 'Ibrahim Hassan',
        accountNumber: '5566778899',
        chequeNumber: 'CHQ-000111',
        amount: 875000,
        requestType: 'DEPOSIT',
        numberOfBoxes: Math.floor(Math.random() * 5) + 1, denominations: [{bill: '1000 Naira', count: Math.floor(875000/1000), total: 875000}],
        phoneNumber: '+2348111112222',
        bankBranch: 'Kaduna Central',
        status: ChequeStatus.FORWARDED_TO_TELLER,
        submittedAt: new Date(NOW - 30000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Teller',
        logs: [
            {
                id: 'log-18',
                chequeId: 'chq-111',
                action: 'SUBMITTED',
                performedBy: 'Ibrahim Hassan',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 30000000).toISOString(),
            },
            {
                id: 'log-19',
                chequeId: 'chq-111',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 25000000).toISOString(),
            },
            {
                id: 'log-20',
                chequeId: 'chq-111',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 20000000).toISOString(),
            },
            {
                id: 'log-21',
                chequeId: 'chq-111',
                action: 'FORWARDED_TO_TELLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 19500000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-112',
        accountName: 'Ngozi Okorie',
        accountNumber: '2211334455',
        chequeNumber: 'CHQ-000112',
        amount: 145000,
        requestType: 'WITHDRAWAL',
        oidMatch: 'OID-'+Math.floor(Math.random()*900000+100000), imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
        phoneNumber: '+2348022223333',
        bankBranch: 'Enugu Main',
        status: ChequeStatus.FORWARDED_TO_TELLER,
        submittedAt: new Date(NOW - 28000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Teller',
        logs: [
            {
                id: 'log-22',
                chequeId: 'chq-112',
                action: 'SUBMITTED',
                performedBy: 'Ngozi Okorie',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 28000000).toISOString(),
            },
            {
                id: 'log-23',
                chequeId: 'chq-112',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 24000000).toISOString(),
            },
            {
                id: 'log-24',
                chequeId: 'chq-112',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 18000000).toISOString(),
            },
            {
                id: 'log-25',
                chequeId: 'chq-112',
                action: 'FORWARDED_TO_TELLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 17500000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-113',
        accountName: 'Samuel Ojo',
        accountNumber: '1020304050',
        chequeNumber: 'CHQ-000113',
        amount: 500000,
        requestType: 'WITHDRAWAL',
        oidMatch: 'OID-'+Math.floor(Math.random()*900000+100000), imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
        phoneNumber: '+2348011223344',
        bankBranch: 'Ikeja Main',
        status: ChequeStatus.FORWARDED_TO_TELLER,
        submittedAt: new Date(NOW - 35000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Teller',
        logs: [
            {
                id: 'log-26',
                chequeId: 'chq-113',
                action: 'SUBMITTED',
                performedBy: 'Samuel Ojo',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 35000000).toISOString(),
            },
            {
                id: 'log-27',
                chequeId: 'chq-113',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 30000000).toISOString(),
            },
            {
                id: 'log-28',
                chequeId: 'chq-113',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 25000000).toISOString(),
            },
            {
                id: 'log-29',
                chequeId: 'chq-113',
                action: 'FORWARDED_TO_TELLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 24500000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-114',
        accountName: 'Grace Aderemi',
        accountNumber: '9988112233',
        chequeNumber: 'CHQ-000114',
        amount: 1250000,
        requestType: 'DEPOSIT',
        numberOfBoxes: Math.floor(Math.random() * 5) + 1, denominations: [{bill: '1000 Naira', count: Math.floor(1250000/1000), total: 1250000}],
        phoneNumber: '+2348033334455',
        bankBranch: 'Victoria Island',
        status: ChequeStatus.FORWARDED_TO_TELLER,
        submittedAt: new Date(NOW - 40000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Teller',
        logs: [
            {
                id: 'log-30',
                chequeId: 'chq-114',
                action: 'SUBMITTED',
                performedBy: 'Grace Aderemi',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 40000000).toISOString(),
            },
            {
                id: 'log-31',
                chequeId: 'chq-114',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 32000000).toISOString(),
            },
            {
                id: 'log-32',
                chequeId: 'chq-114',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 28000000).toISOString(),
            },
            {
                id: 'log-33',
                chequeId: 'chq-114',
                action: 'FORWARDED_TO_TELLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 27500000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-115',
        accountName: 'Opeyemi Balogun',
        accountNumber: '4455667788',
        chequeNumber: 'CHQ-000115',
        amount: 2500000,
        requestType: 'DEPOSIT',
        numberOfBoxes: Math.floor(Math.random() * 5) + 1, denominations: [{bill: '1000 Naira', count: Math.floor(2500000/1000), total: 2500000}],
        phoneNumber: '+2348055556666',
        bankBranch: 'Lekki Phase 1',
        status: ChequeStatus.AUTHORIZED_BY_TELLER,
        submittedAt: new Date(NOW - 50000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Treasury',
        logs: [
            {
                id: 'log-34',
                chequeId: 'chq-115',
                action: 'SUBMITTED',
                performedBy: 'Opeyemi Balogun',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 50000000).toISOString(),
            },
            {
                id: 'log-35',
                chequeId: 'chq-115',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 45000000).toISOString(),
            },
            {
                id: 'log-36',
                chequeId: 'chq-115',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 40000000).toISOString(),
            },
            {
                id: 'log-37',
                chequeId: 'chq-115',
                action: 'FORWARDED_TO_TELLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 39000000).toISOString(),
            },
            {
                id: 'log-38',
                chequeId: 'chq-115',
                action: 'AUTHORIZED_BY_TELLER',
                performedBy: 'Alice Wong',
                performedByRole: UserRole.TELLER,
                timestamp: new Date(NOW - 30000000).toISOString(),
            }
        ],
    },
    {
        id: 'chq-116',
        accountName: 'Chima Anyanwu',
        accountNumber: '1122334455',
        chequeNumber: 'CHQ-000116',
        amount: 850000,
        requestType: 'DEPOSIT',
        numberOfBoxes: Math.floor(Math.random() * 5) + 1, denominations: [{bill: '1000 Naira', count: Math.floor(850000/1000), total: 850000}],
        phoneNumber: '+2348122223333',
        bankBranch: 'Festac Town',
        status: ChequeStatus.AUTHORIZED_BY_TELLER,
        submittedAt: new Date(NOW - 60000000).toISOString(),
        submittedBy: 'u2',
        currentOffice: 'Treasury',
        logs: [
            {
                id: 'log-39',
                chequeId: 'chq-116',
                action: 'SUBMITTED',
                performedBy: 'Chima Anyanwu',
                performedByRole: UserRole.USER,
                timestamp: new Date(NOW - 60000000).toISOString(),
            },
            {
                id: 'log-40',
                chequeId: 'chq-116',
                action: 'APPROVED_BY_CUSTOMER_SERVICE',
                performedBy: 'Sarah Smith',
                performedByRole: UserRole.CUSTOMER_SERVICE,
                timestamp: new Date(NOW - 55000000).toISOString(),
            },
            {
                id: 'log-41',
                chequeId: 'chq-116',
                action: 'VERIFIED_BY_BRANCH_CONTROLLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 50000000).toISOString(),
            },
            {
                id: 'log-42',
                chequeId: 'chq-116',
                action: 'FORWARDED_TO_TELLER',
                performedBy: 'Mike Johnson',
                performedByRole: UserRole.BRANCH_CONTROLLER,
                timestamp: new Date(NOW - 45000000).toISOString(),
            },
            {
                id: 'log-43',
                chequeId: 'chq-116',
                action: 'AUTHORIZED_BY_TELLER',
                performedBy: 'Alice Wong',
                performedByRole: UserRole.TELLER,
                timestamp: new Date(NOW - 40000000).toISOString(),
            }
        ],
    }
];
